name: Deploy ke cPanel Biznet GIO

on:
  push:
    branches:
      - main  # Memicu otomatisasi setiap ada push ke branch main

jobs:
  web-deploy:
    name: 🎉 Deploy file ke Webhosting
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Ambil Kode Terbaru dari Github
      uses: actions/checkout@v4
    
    - name: 📂 Sinkronisasi File via FTP
      uses: SamKirkland/FTP-Deploy-Action@v4.3.5
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        server-dir: public_html/shajiera.id/kelulusan  # Ubah ke public_html/kelulusan/ jika ingin masuk sub-folder